<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<!-- Kafka -->
		<PackageReference Include="Confluent.Kafka" Version="2.14.0" />

		<!-- EF Core (PostgreSQL ONLY for Render) -->
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.7" />

		<!-- PostgreSQL Provider (THIS FIXES UseNpgsql ERROR) -->
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />

		<!-- EF Core Tools -->
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.7">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.7">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<!-- Swagger -->
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LogStreamX.Contracts\LogStreamX.Contracts.csproj" />
		<ProjectReference Include="..\LogStreamX.Infrastructure\LogStreamX.Infrastructure.csproj" />
	</ItemGroup>

</Project>